wmake: wcat.c wgrep.c wzip.c wunzip.c
	gcc -o ./wcat/wcat wcat.c -Wall -Werror
	gcc -o ./wgrep/wgrep wgrep.c -Wall -Werror
	gcc -o ./wzip/wzip wzip.c -Wall -Werror
	gcc -o ./wunzip/wunzip wunzip.c -Wall -Werror
